package Automat.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum CoinType {
  _1("1", 1),
  _2("2", 2),
  _5("5", 5),
  _10("10", 10),
  _20("20", 20),
  _50("50", 50),
  _100("100", 100),
  _200("200", 200);

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public static List<CoinType> getConstants() {
    List<CoinType> list = ListSequence.fromList(new LinkedList<CoinType>());
    ListSequence.fromList(list).addElement(CoinType._1);
    ListSequence.fromList(list).addElement(CoinType._2);
    ListSequence.fromList(list).addElement(CoinType._5);
    ListSequence.fromList(list).addElement(CoinType._10);
    ListSequence.fromList(list).addElement(CoinType._20);
    ListSequence.fromList(list).addElement(CoinType._50);
    ListSequence.fromList(list).addElement(CoinType._100);
    ListSequence.fromList(list).addElement(CoinType._200);
    return list;
  }

  public static CoinType getDefault() {
    return null;
  }

  public static CoinType parseValue(String value) {
    if (value == null) {
      return CoinType.getDefault();
    }
    if (value.equals(CoinType._1.getValueAsString())) {
      return CoinType._1;
    }
    if (value.equals(CoinType._2.getValueAsString())) {
      return CoinType._2;
    }
    if (value.equals(CoinType._5.getValueAsString())) {
      return CoinType._5;
    }
    if (value.equals(CoinType._10.getValueAsString())) {
      return CoinType._10;
    }
    if (value.equals(CoinType._20.getValueAsString())) {
      return CoinType._20;
    }
    if (value.equals(CoinType._50.getValueAsString())) {
      return CoinType._50;
    }
    if (value.equals(CoinType._100.getValueAsString())) {
      return CoinType._100;
    }
    if (value.equals(CoinType._200.getValueAsString())) {
      return CoinType._200;
    }
    return CoinType.getDefault();
  }

  private int myValue;

  CoinType(String name, int value) {
    this.myName = name;
    this.myValue = value;
  }

  public int getValue() {
    return this.myValue;
  }
}
