package Automat.sandbox;

/*Generated by MPS */


public class AutomatException extends Exception {
  public AutomatException() {
    super();
  }

  public AutomatException(String msg) {
    super(msg);
  }
}
