package Automat.sandbox;

/*Generated by MPS */


public class ChangeItemIdCommand implements ICommand {
  private String addedString;

  public ChangeItemIdCommand(String addedString) {
    this.addedString = addedString;
  }

  @Override
  public void execute(Automat automat) {
    automat.addToCurrentId(addedString);
  }


}
