package Automat.sandbox;

/*Generated by MPS */


public class ClearItemIdCommand implements ICommand {
  public ClearItemIdCommand() {
  }

  @Override
  public void execute(Automat automat) {
    automat.clearCurrentId();
  }


}
