package Automat.sandbox;

/*Generated by MPS */


public class InsertMoneyCommand implements ICommand {
  private int value;

  public InsertMoneyCommand(int value) {
    this.value = value;
  }

  @Override
  public void execute(Automat automat) throws ValueNotAcceptedException, NotEnoughChangeException, NoItemSelectedException {
    automat.insertMoney(value);
  }


}
