package Automat.sandbox;

/*Generated by MPS */


public class InsertCardCommand implements ICommand {
  private String card;

  public InsertCardCommand(String card) {
    this.card = card;
  }

  @Override
  public void execute(Automat automat) throws NotEnoughChangeException, NoPartialCardPaymentException, NoItemSelectedException {
    automat.payWithCard(card);
  }


}
