package Automat.sandbox;

/*Generated by MPS */


public class SelectItemCommand implements ICommand {
  public SelectItemCommand() {
  }

  @Override
  public void execute(Automat automat) throws AutomatException {
    automat.selectItem();
  }


}
