package Automat.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorHint;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {
  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0a, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Automat_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new accepts_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new accepts_banknotes_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new accepts_coins_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new accepts_creditcard_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new has_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new stores_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new stores_items_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new stores_items_item_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new stores_money_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new stores_money_banknotes_Editor());
      case 11:
        return Collections.<ConceptEditor>singletonList(new stores_money_coins_Editor());
      default:
    }
    return Collections.emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.emptyList();
  }



  public Collection<ConceptEditorHint> getHints() {
    return Collections.emptyList();
  }


  private static String[] stringSwitchCases_xbvbvu_a0a0a = new String[]{"Automat.structure.Automat", "Automat.structure.accepts", "Automat.structure.accepts_banknotes", "Automat.structure.accepts_coins", "Automat.structure.accepts_creditcard", "Automat.structure.has", "Automat.structure.stores", "Automat.structure.stores_items", "Automat.structure.stores_items_item", "Automat.structure.stores_money", "Automat.structure.stores_money_banknotes", "Automat.structure.stores_money_coins"};
}
