package Automat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class accepts_coins_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public accepts_coins_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Automat.structure.accepts_coins";
  }
}
