package Automat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class accepts_banknotes_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public accepts_banknotes_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Automat.structure.accepts_banknotes";
  }
}
