package Automat.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new Automat_BehaviorDescriptor();
      case 5:
        return new has_BehaviorDescriptor();
      case 1:
        return new accepts_BehaviorDescriptor();
      case 3:
        return new accepts_coins_BehaviorDescriptor();
      case 2:
        return new accepts_banknotes_BehaviorDescriptor();
      case 4:
        return new accepts_creditcard_BehaviorDescriptor();
      case 6:
        return new stores_BehaviorDescriptor();
      case 9:
        return new stores_money_BehaviorDescriptor();
      case 11:
        return new stores_money_coins_BehaviorDescriptor();
      case 10:
        return new stores_money_banknotes_BehaviorDescriptor();
      case 7:
        return new stores_items_BehaviorDescriptor();
      case 8:
        return new stores_items_item_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"Automat.structure.Automat", "Automat.structure.accepts", "Automat.structure.accepts_banknotes", "Automat.structure.accepts_coins", "Automat.structure.accepts_creditcard", "Automat.structure.has", "Automat.structure.stores", "Automat.structure.stores_items", "Automat.structure.stores_items_item", "Automat.structure.stores_money", "Automat.structure.stores_money_banknotes", "Automat.structure.stores_money_coins"};
}
