package Automat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class has_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public has_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Automat.structure.has";
  }
}
