package Automat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class stores_money_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public stores_money_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Automat.structure.stores_money";
  }
}
