package Automat.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_8675345724943758056(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), "_has", true), "type", null).equals("coffee");
  }

  public static boolean baseMappingRule_Condition_8675345724947531861(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return (int) ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "_stores", true), "money", true), "money_banknotes", true)).count() == 0;
  }

  public static boolean baseMappingRule_Condition_8675345724943871324(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), "_has", true), "type", null).equals("coffee");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891000170791(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "_has", true), "color_r");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891000203579(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "_has", true), "color_g");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891000296687(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "_has", true), "color_b");
  }

  public static Object propertyMacro_GetPropertyValue_8675345724950040061(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), "_has", true), "type", null);
  }

  public static Object propertyMacro_GetPropertyValue_6119712891006726698(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "numcode");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891006753275(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891006778565(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "price");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891006785776(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "quantity");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891003663943(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "coinType");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891003712750(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "quantity");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891004908429(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "banknoteType");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891004951990(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "quantity");
  }

  public static Object propertyMacro_GetPropertyValue_166346444447514868(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "cardtype");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891007264183(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6119712890999875985(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "_has", true), "currency");
  }

  public static Object propertyMacro_GetPropertyValue_6119712891001181584(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "_has", true), "language");
  }

  public static Object propertyMacro_GetPropertyValue_8675345724950219835(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), "_has", true), "type", null);
  }

  public static Object propertyMacro_GetPropertyValue_8675345724950239329(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), "_has", true), "type", null);
  }

  public static Iterable sourceNodesQuery_6119712891006637702(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "_stores", true), "items", true), "items_item", true);
  }

  public static Iterable sourceNodesQuery_6119712891003597423(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "_stores", true), "money", true), "money_coins", true);
  }

  public static Iterable sourceNodesQuery_6119712891004846795(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "_stores", true), "money", true), "money_banknotes", true);
  }

  public static Iterable sourceNodesQuery_166346444447430698(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "_accepts", true), "_accepts_creditcard", true);
  }
}
